import '../models/entry.dart';
import 'date_utils.dart';

/// Pre-loaded, clearly-marked sample entries shown on first run so the Cupboard
/// doesn't land empty. Cleared automatically the moment the user logs a real cup.
List<Entry> sampleEntries([DateTime? now]) {
  final today = todayDate(now);
  DateTime d(int offset) => offsetDate(today, offset);

  return [
    Entry(
      id: Entry.newId(),
      kind: EntryKind.home,
      date: d(0),
      method: 'Pour-over (V60)',
      price: 28,
      rating: 4,
      caption: 'Bright and a little floral. Good start.',
      timeOfDay: DayPart.morning,
      flavors: const ['Floral', 'Bright/Acidic'],
      roast: Roast.light,
      isSample: true,
    ),
    Entry(
      id: Entry.newId(),
      kind: EntryKind.away,
      date: d(-1),
      venueTag: VenueTag.cafe,
      venueName: 'Yardstick Coffee',
      method: 'Espresso',
      price: 160,
      rating: 5,
      caption: 'Worth the hype, honestly.',
      timeOfDay: DayPart.afternoon,
      flavors: const ['Chocolatey', 'Caramel'],
      roast: Roast.medium,
      isSample: true,
    ),
    Entry(
      id: Entry.newId(),
      kind: EntryKind.home,
      date: d(-2),
      method: 'French press',
      price: 28,
      rating: 3,
      timeOfDay: DayPart.morning,
      flavors: const ['Earthy'],
      roast: Roast.dark,
      isSample: true,
    ),
    Entry(
      id: Entry.newId(),
      kind: EntryKind.away,
      date: d(-3),
      venueTag: VenueTag.convenience,
      venueName: '7-Eleven',
      method: 'Instant',
      price: 35,
      rating: 2,
      caption: 'Fuel, not flavor.',
      timeOfDay: DayPart.morning,
      flavors: const ['Bitter'],
      roast: Roast.dark,
      isSample: true,
    ),
    Entry(
      id: Entry.newId(),
      kind: EntryKind.home,
      date: d(-4),
      method: 'Pour-over (V60)',
      price: 28,
      rating: 4,
      timeOfDay: DayPart.morning,
      flavors: const ['Fruity', 'Floral'],
      roast: Roast.light,
      isSample: true,
    ),
    Entry(
      id: Entry.newId(),
      kind: EntryKind.away,
      date: d(-6),
      venueTag: VenueTag.cafe,
      venueName: 'Wildflour Café',
      method: 'Cold brew',
      price: 175,
      rating: 4,
      caption: 'Sat outside, good people-watching.',
      timeOfDay: DayPart.afternoon,
      flavors: const ['Fruity', 'Nutty'],
      roast: Roast.medium,
      isSample: true,
    ),
    Entry(
      id: Entry.newId(),
      kind: EntryKind.home,
      date: d(-7),
      method: 'AeroPress',
      price: 28,
      rating: 5,
      caption: 'Finally nailed the ratio.',
      timeOfDay: DayPart.morning,
      flavors: const ['Chocolatey'],
      roast: Roast.medium,
      isSample: true,
    ),
    Entry(
      id: Entry.newId(),
      kind: EntryKind.away,
      date: d(-9),
      venueTag: VenueTag.cafe,
      venueName: 'Yardstick Coffee',
      method: 'Espresso',
      price: 160,
      rating: 5,
      timeOfDay: DayPart.morning,
      flavors: const ['Caramel', 'Nutty'],
      roast: Roast.medium,
      isSample: true,
    ),
    Entry(
      id: Entry.newId(),
      kind: EntryKind.away,
      date: d(-11),
      venueTag: VenueTag.office,
      venueName: 'Office pantry',
      method: 'Instant',
      price: 0,
      free: true,
      rating: 2,
      caption: 'Free is free.',
      timeOfDay: DayPart.morning,
      flavors: const ['Bitter'],
      roast: Roast.dark,
      isSample: true,
    ),
    Entry(
      id: Entry.newId(),
      kind: EntryKind.home,
      date: d(-13),
      method: 'Moka pot',
      price: 28,
      rating: 4,
      timeOfDay: DayPart.evening,
      flavors: const ['Earthy', 'Bitter'],
      roast: Roast.dark,
      isSample: true,
    ),
  ];
}
